### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by mazgor** [tobiaszimmermann1/pot-plugin#36]
While testing the plugin I installed and uninstalled the plugin a few times. Sometimes via Wordpress, sometimes via FTP. Now I only get a blank screen. It doesn't seem to be a plugin conflict. I deactivated all plugins but woocommerce, but it still get a blank screen when I click on the Foodcoop link in the Wordpress backend. Maybe there is something that doesn't work when working with FTP? I don't remember exactly, but I think it only happened after I once tried to install the dev-version.

**Comment by tobiaszimmermann1** [comment]
Regenerate permalinks: https://www.wpbeginner.com/beginners-guide/how-to-regenerate-your-permalinks-in-wordpress/

**Comment by mazgor** [comment]
> Regenerate permalinks: https://www.wpbeginner.com/beginners-guide/how-to-regenerate-your-permalinks-in-wordpress/

This didn't help. The blank screen is in the backend. The Plugin site in the backend is just not showing. 'Produkte Import' is showing, but not 'Foodcoop'. What could be the reason?

![Image](https://github.com/user-attachments/assets/b562f044-a101-4361-b742-1a6e2bf01405)
