### ISSUE TITLE
Export QR-Code

### ISSUE THREAD

**Issue by mazgor** [tobiaszimmermann1/pot-plugin#37]
It would be great, if the QR-Code for self-checkout (and all other foodcoop data fields) could be made available to export via a regular woocommerce product export. In my case mainly in order to be able to design/create individual product labels using data from the foodcoop app but also 'regular' wordpress product data.

**Comment by tobiaszimmermann1** [comment]
The content of the QR Code is simpy the products SKU. You can create your own QR Codes from SKUs and design them however you wish.
