### ISSUE TITLE
Produktbild erfassen nicht möglich

### ISSUE THREAD

**Issue by Laebesmittelpunkt** [tobiaszimmermann1/pot-plugin#41]
Bei einigen Produkten ist keine Erfassung des Produktbildes möglich, da die Fehlermeldung im Screenshot kommt. Es sind Produkte, bei denen ich früher schon einmal ein Produktbild erfasst hatte, bevor die Produktbilderfassung überarbeitet wurde.

![Produktbild erfassen](https://github.com/user-attachments/assets/e96d683a-4bcd-4a34-a59c-2b0d833e02c0)

**Comment by tobiaszimmermann1** [comment]
#39 fixed with 1.7.5
